version: "3"
services:
  nginx:
    ports:
      - "8080:80"
  node-app:
    ports:
      - "8001:5005"
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    env_file: .env
    command: npm run dev
    mem_limit: 2g

  mongo:
    env_file:
      - .env
    ports:
      - "27017:27017"
